language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 5.0
solution: FeshShop.Identity.sln
before_install:
  - chmod +x ./scripts/dotnet-restore.sh 
install:
  - travis_wait ./scripts/dotnet-restore.sh
before_script:
  - chmod +x ./scripts/dotnet-build.sh 
script:
  - ./scripts/dotnet-build.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "main" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
    docker build .
    docker push "$DOCKER_USERNAME"/feshshop.identity:latest
  fi

branches:
  only:
  - main
  - dev
notifications:
  email:
    on_success: never
    on_failure: never
